- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      tags:
      - zsh
      - node
  tasks:
    - include: fem-tasks/zsh.yml
    - include: fem-tasks/node.yml
