#!/usr/bin/env bash

session=$(find ~ ~/workspace ~/learning -mindepth 1 -maxdepth 1 -type d | fzf)

# tr finds characters in input and replaces them with corresponding character of output
# I.E. we replace . with _
session_name=$(basename "$session" | tr . _)

# If has-session is running on a session that doesn't exist it will put a message to sout
# we use the 2> to pipe that into the garbage can '/dev/null'
if ! tmux has-session -t "$session_name" 2> /dev/null; then
	tmux new-session -s "$session_name" -c "$session" -d
fi

tmux switch-client -t "$session_name"
